name: movies-go-instance2

services:
  db2:
    image: postgres:16-alpine
    container_name: movies-api-db2
    restart: unless-stopped
    command: postgres -c jit=off
    environment:
      POSTGRES_USER: movies_api
      POSTGRES_PASSWORD: movies_api
      POSTGRES_DB: movies_api
    volumes:
      - pg_data2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U movies_api -d movies_api"]
      interval: 5s
      timeout: 3s
      retries: 10

  app2:
    build: .
    container_name: movies-api-2
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    environment:
      - DATABASE_URL=postgres://movies_api:movies_api@db2:5432/movies_api?sslmode=disable
      - PORT=8888
    ports:
      - "8889:8888"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./plugins:/app/plugins
      - logs_data2:/app/logs
      - cache_data2:/app/cache
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      db2:
        condition: service_healthy

volumes:
  pg_data2:
  logs_data2:
  cache_data2:
